apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "torch-iris"
spec:
  predictor:
    model:
      modelFormat:
        name: pytorch
      storageUri: "file:/home/jovyan/iris" 
